FROM php:8.2 AS builder

RUN apt-get update && \
    apt-get install -y unzip libzip-dev && \
    docker-php-ext-install zip

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('sha384', 'composer-setup.php') === 'c8b085408188070d5f52bcfe4ecfbee5f727afa458b2573b8eaaf77b3419b0bf2768dc67c86944da1544f06fa544fd47') { echo 'Instalador verificado'.PHP_EOL; } else { echo 'Instalador corrompido'.PHP_EOL; unlink('composer-setup.php'); exit(1); }" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer

WORKDIR /var/www

RUN composer create-project laravel/laravel meu-laravel

FROM php:8.2-fpm-alpine
WORKDIR /var/www
RUN rm -rf /var/www/html

COPY --from=builder /var/www/meu-laravel .

RUN chown -R www-data:www-data /var/www

EXPOSE 9000

CMD [ "php-fpm" ]